"""Add user_id to category table

Revision ID: ba5a17827160
Revises: 7dc18f4d716a
Create Date: 2026-03-03 21:38:11.907420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba5a17827160'
down_revision: Union[str, Sequence[str], None] = '7dc18f4d716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
