"""Add category table

Revision ID: 7dc18f4d716a
Revises: 6a107ec6d15e
Create Date: 2026-03-03 21:28:57.504007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7dc18f4d716a'
down_revision: Union[str, Sequence[str], None] = '6a107ec6d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'SAVING', name='categorytype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_type'), 'category', ['type'], unique=False)
    op.add_column('budget', sa.Column('value', sa.Float(), nullable=False))
    op.add_column('budget', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_budget_category_id'), 'budget', ['category_id'], unique=False)
    op.create_foreign_key(None, 'budget', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_index(op.f('ix_budget_category_id'), table_name='budget')
    op.drop_column('budget', 'category_id')
    op.drop_column('budget', 'value')
    op.drop_index(op.f('ix_category_type'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
