"""Add cascade delete budget on category

Revision ID: 020eaf4f5dd6
Revises: ba5a17827160
Create Date: 2026-03-03 21:48:38.522880

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '020eaf4f5dd6'
down_revision: Union[str, Sequence[str], None] = 'ba5a17827160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__budget__category__3D5E1FD2'), 'budget', type_='foreignkey')
    op.create_foreign_key(None, 'budget', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.create_foreign_key(op.f('FK__budget__category__3D5E1FD2'), 'budget', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
