"""Add reoccur to category

Revision ID: 32bbe059a9ea
Revises: 389891ccb1f3
Create Date: 2026-03-04 19:27:58.855978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bbe059a9ea'
down_revision: Union[str, Sequence[str], None] = '389891ccb1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('reoccur', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_index(op.f('ix_category_reoccur'), 'category', ['reoccur'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_reoccur'), table_name='category')
    op.drop_column('category', 'reoccur')
    # ### end Alembic commands ###
