"""Add reoccur and cloned_from_id to budget

Revision ID: dcad8f0a8ed6
Revises: 32bbe059a9ea
Create Date: 2026-03-04 19:41:08.207994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcad8f0a8ed6'
down_revision: Union[str, Sequence[str], None] = '32bbe059a9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('reoccur', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('budget', sa.Column('cloned_from_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_budget_cloned_from_id'), 'budget', ['cloned_from_id'], unique=False)
    op.create_index(op.f('ix_budget_reoccur'), 'budget', ['reoccur'], unique=False)
    op.create_foreign_key(None, 'budget', 'budget', ['cloned_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_index(op.f('ix_budget_reoccur'), table_name='budget')
    op.drop_index(op.f('ix_budget_cloned_from_id'), table_name='budget')
    op.drop_column('budget', 'cloned_from_id')
    op.drop_column('budget', 'reoccur')
    # ### end Alembic commands ###
