"""Remove reoccur from category

Revision ID: f1bbec6474cb
Revises: dcad8f0a8ed6
Create Date: 2026-03-04 19:48:45.240004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'f1bbec6474cb'
down_revision: Union[str, Sequence[str], None] = 'dcad8f0a8ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_reoccur'), table_name='category')
    # SQL Server requires dropping the default constraint before the column
    op.execute("""
        DECLARE @constraint NVARCHAR(256);
        SELECT @constraint = name FROM sys.default_constraints
        WHERE parent_object_id = OBJECT_ID('category') AND COL_NAME(parent_object_id, parent_column_id) = 'reoccur';
        IF @constraint IS NOT NULL
            EXEC('ALTER TABLE category DROP CONSTRAINT [' + @constraint + ']');
    """)
    op.drop_column('category', 'reoccur')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('reoccur', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_category_reoccur'), 'category', ['reoccur'], unique=False)
    # ### end Alembic commands ###
