"""replace date with year and month in budget

Revision ID: 389891ccb1f3
Revises: 020eaf4f5dd6
Create Date: 2026-03-03 22:44:37.992964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '389891ccb1f3'
down_revision: Union[str, Sequence[str], None] = '020eaf4f5dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('budget', sa.Column('month', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_budget_date'), table_name='budget')
    op.create_index(op.f('ix_budget_month'), 'budget', ['month'], unique=False)
    op.create_index(op.f('ix_budget_year'), 'budget', ['year'], unique=False)
    op.drop_column('budget', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('date', sa.DATETIME(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_budget_year'), table_name='budget')
    op.drop_index(op.f('ix_budget_month'), table_name='budget')
    op.create_index(op.f('ix_budget_date'), 'budget', ['date'], unique=False)
    op.drop_column('budget', 'month')
    op.drop_column('budget', 'year')
    # ### end Alembic commands ###
